// AslanApp/Model/QuizData.swift
import Foundation

struct QuizData {

    // --- BEGINNER QUIZZES ---
    static let hiraganaBasicsQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Romaji for 'あ'?", options: [QuizOption(text: "a", isCorrect: true), QuizOption(text: "i", isCorrect: false), QuizOption(text: "u", isCorrect: false), QuizOption(text: "o", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'き'?", options: [QuizOption(text: "ka", isCorrect: false), QuizOption(text: "ki", isCorrect: true), QuizOption(text: "ku", isCorrect: false), QuizOption(text: "ke", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'み' is 'mi'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Which Hiragana is 'se'?", options: [QuizOption(text: "さ", isCorrect: false), QuizOption(text: "す", isCorrect: false), QuizOption(text: "せ", isCorrect: true), QuizOption(text: "そ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Hiragana for 'no'?", options: [QuizOption(text: "な", isCorrect: false), QuizOption(text: "に", isCorrect: false), QuizOption(text: "ぬ", isCorrect: false), QuizOption(text: "の", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'つ'?", options: [QuizOption(text: "tsu", isCorrect: true), QuizOption(text: "chi", isCorrect: false), QuizOption(text: "ta", isCorrect: false), QuizOption(text: "te", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Hiragana is 'ha'?", options: [QuizOption(text: "ほ", isCorrect: false), QuizOption(text: "は", isCorrect: true), QuizOption(text: "ひ", isCorrect: false), QuizOption(text: "ふ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'ゆ' is 'yu'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Romaji for 'め'?", options: [QuizOption(text: "ma", isCorrect: false), QuizOption(text: "mi", isCorrect: false), QuizOption(text: "mu", isCorrect: false), QuizOption(text: "me", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Hiragana for 're'?", options: [QuizOption(text: "ら", isCorrect: false), QuizOption(text: "り", isCorrect: false), QuizOption(text: "る", isCorrect: false), QuizOption(text: "れ", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'ね'?", options: [QuizOption(text: "na", isCorrect: false), QuizOption(text: "ne", isCorrect: true), QuizOption(text: "nu", isCorrect: false), QuizOption(text: "ni", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'ほ' is 'ho'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Which Hiragana is 'wo'?", options: [QuizOption(text: "わ", isCorrect: false), QuizOption(text: "を", isCorrect: true), QuizOption(text: "ん", isCorrect: false), QuizOption(text: "ろ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Hiragana for 'yo'?", options: [QuizOption(text: "や", isCorrect: false), QuizOption(text: "ゆ", isCorrect: false), QuizOption(text: "よ", isCorrect: true), QuizOption(text: "わ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'ち'?", options: [QuizOption(text: "chi", isCorrect: true), QuizOption(text: "tsu", isCorrect: false), QuizOption(text: "te", isCorrect: false), QuizOption(text: "to", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Hiragana is 'nu'?", options: [QuizOption(text: "な", isCorrect: false), QuizOption(text: "に", isCorrect: false), QuizOption(text: "ぬ", isCorrect: true), QuizOption(text: "ね", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'え' is 'e'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Romaji for 'こ'?", options: [QuizOption(text: "ka", isCorrect: false), QuizOption(text: "ki", isCorrect: false), QuizOption(text: "ku", isCorrect: false), QuizOption(text: "ko", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Hiragana for 'shi'?", options: [QuizOption(text: "さ", isCorrect: false), QuizOption(text: "し", isCorrect: true), QuizOption(text: "す", isCorrect: false), QuizOption(text: "せ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'ふ'?", options: [QuizOption(text: "fu", isCorrect: true), QuizOption(text: "he", isCorrect: false), QuizOption(text: "ho", isCorrect: false), QuizOption(text: "ha", isCorrect: false)], questionType: .multipleChoice)
    ]

    static let katakanaBasicsQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Romaji for 'ア'?", options: [QuizOption(text: "a", isCorrect: true), QuizOption(text: "e", isCorrect: false), QuizOption(text: "o", isCorrect: false), QuizOption(text: "i", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'シ'?", options: [QuizOption(text: "tsu", isCorrect: false), QuizOption(text: "so", isCorrect: false), QuizOption(text: "shi", isCorrect: true), QuizOption(text: "n", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'ヌ' is 'nu'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Which Katakana is 'to'?", options: [QuizOption(text: "タ", isCorrect: false), QuizOption(text: "チ", isCorrect: false), QuizOption(text: "ツ", isCorrect: false), QuizOption(text: "ト", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Katakana for 'he'?", options: [QuizOption(text: "ハ", isCorrect: false), QuizOption(text: "ヒ", isCorrect: false), QuizOption(text: "フ", isCorrect: false), QuizOption(text: "ヘ", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'マ'?", options: [QuizOption(text: "ma", isCorrect: true), QuizOption(text: "mi", isCorrect: false), QuizOption(text: "mu", isCorrect: false), QuizOption(text: "me", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Katakana is 'yo'?", options: [QuizOption(text: "ヤ", isCorrect: false), QuizOption(text: "ユ", isCorrect: false), QuizOption(text: "ヨ", isCorrect: true), QuizOption(text: "ラ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'リ' is 'ri'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Romaji for 'ワ'?", options: [QuizOption(text: "ra", isCorrect: false), QuizOption(text: "wa", isCorrect: true), QuizOption(text: "wo", isCorrect: false), QuizOption(text: "n", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Katakana for 'ke'?", options: [QuizOption(text: "カ", isCorrect: false), QuizOption(text: "キ", isCorrect: false), QuizOption(text: "ク", isCorrect: false), QuizOption(text: "ケ", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'ソ'?", options: [QuizOption(text: "sa", isCorrect: false), QuizOption(text: "shi", isCorrect: false), QuizOption(text: "su", isCorrect: false), QuizOption(text: "so", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'ム' is 'mu'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Which Katakana is 'ru'?", options: [QuizOption(text: "ラ", isCorrect: false), QuizOption(text: "リ", isCorrect: false), QuizOption(text: "ル", isCorrect: true), QuizOption(text: "レ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Katakana for 'fu'?", options: [QuizOption(text: "ハ", isCorrect: false), QuizOption(text: "ヒ", isCorrect: false), QuizOption(text: "フ", isCorrect: true), QuizOption(text: "ヘ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'ン'?", options: [QuizOption(text: "m", isCorrect: false), QuizOption(text: "n", isCorrect: true), QuizOption(text: "o", isCorrect: false), QuizOption(text: "i", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Katakana is 'ko'?", options: [QuizOption(text: "カ", isCorrect: false), QuizOption(text: "キ", isCorrect: false), QuizOption(text: "ク", isCorrect: false), QuizOption(text: "コ", isCorrect: true)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'テ' is 'te'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Romaji for 'イ'?", options: [QuizOption(text: "a", isCorrect: false), QuizOption(text: "i", isCorrect: true), QuizOption(text: "u", isCorrect: false), QuizOption(text: "e", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the Katakana for 'tsu'?", options: [QuizOption(text: "タ", isCorrect: false), QuizOption(text: "チ", isCorrect: false), QuizOption(text: "ツ", isCorrect: true), QuizOption(text: "テ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Romaji for 'ロ'?", options: [QuizOption(text: "ra", isCorrect: false), QuizOption(text: "ri", isCorrect: false), QuizOption(text: "ru", isCorrect: false), QuizOption(text: "ro", isCorrect: true)], questionType: .multipleChoice)
    ]

    static let kanjiN5StarterQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Meaning of '人'?", options: [QuizOption(text: "Mountain", isCorrect: false), QuizOption(text: "Person", isCorrect: true), QuizOption(text: "Tree", isCorrect: false), QuizOption(text: "River", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji is 'fire' (火)?", options: [QuizOption(text: "水", isCorrect: false), QuizOption(text: "木", isCorrect: false), QuizOption(text: "火", isCorrect: true), QuizOption(text: "土", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '一' (one)?", options: [QuizOption(text: "ひと", isCorrect: false), QuizOption(text: "イチ / イツ", isCorrect: true), QuizOption(text: "カ / コ", isCorrect: false), QuizOption(text: "ジン / ニン", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '月' (moon/month)?", options: [QuizOption(text: "ニチ", isCorrect: false), QuizOption(text: "ゲツ / ガツ", isCorrect: false), QuizOption(text: "つき", isCorrect: true), QuizOption(text: "ひ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'年' means 'year'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Which Kanji means 'big' (大)?", options: [QuizOption(text: "小", isCorrect: false), QuizOption(text: "中", isCorrect: false), QuizOption(text: "大", isCorrect: true), QuizOption(text: "人", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '本'?", options: [QuizOption(text: "Tree", isCorrect: false), QuizOption(text: "Book / Origin", isCorrect: true), QuizOption(text: "Sun", isCorrect: false), QuizOption(text: "Time", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '国' (country)?", options: [QuizOption(text: "くに", isCorrect: false), QuizOption(text: "ジン", isCorrect: false), QuizOption(text: "コク", isCorrect: true), QuizOption(text: "ネン", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '見' (see)?", options: [QuizOption(text: "ケン", isCorrect: false), QuizOption(text: "み.る", isCorrect: true), QuizOption(text: "ギョウ", isCorrect: false), QuizOption(text: "シュツ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'時' means 'time/hour'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Meaning of '中'?", options: [QuizOption(text: "Outside", isCorrect: false), QuizOption(text: "Middle, Inside", isCorrect: true), QuizOption(text: "Small", isCorrect: false), QuizOption(text: "High", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji is 'long' (長)?", options: [QuizOption(text: "短", isCorrect: false), QuizOption(text: "小", isCorrect: false), QuizOption(text: "長", isCorrect: true), QuizOption(text: "太", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '出' (exit)?", options: [QuizOption(text: "で", isCorrect: false), QuizOption(text: "シュツ / スイ", isCorrect: true), QuizOption(text: "はい", isCorrect: false), QuizOption(text: "ニュウ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '行' (go)?", options: [QuizOption(text: "コウ", isCorrect: false), QuizOption(text: "ギョウ", isCorrect: false), QuizOption(text: "い.く / ゆ.く", isCorrect: true), QuizOption(text: "くる", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'分' means 'understand' or 'minute'. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Meaning of '前'?", options: [QuizOption(text: "Back", isCorrect: false), QuizOption(text: "Left", isCorrect: false), QuizOption(text: "Before, Front", isCorrect: true), QuizOption(text: "Right", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji is 'two' (二)?", options: [QuizOption(text: "一", isCorrect: false), QuizOption(text: "三", isCorrect: false), QuizOption(text: "二", isCorrect: true), QuizOption(text: "四", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '生' (life)?", options: [QuizOption(text: "い.きる", isCorrect: false), QuizOption(text: "なま", isCorrect: false), QuizOption(text: "セイ / ショウ", isCorrect: true), QuizOption(text: "う.まれる", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '後' (after)?", options: [QuizOption(text: "ゴ", isCorrect: false), QuizOption(text: "コウ", isCorrect: false), QuizOption(text: "のち / うし.ろ / あと", isCorrect: true), QuizOption(text: "まえ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'十' means 'thousand'. True or False?", options: [QuizOption(text: "False", isCorrect: true), QuizOption(text: "True", isCorrect: false)], questionType: .trueFalse)
    ]

    // --- INTERMEDIATE QUIZZES (Contoh Awal) ---
    static let intermediateGrammarParticlesQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Particle for direct object?", options: [QuizOption(text: "は", isCorrect: false), QuizOption(text: "が", isCorrect: false), QuizOption(text: "を", isCorrect: true), QuizOption(text: "に", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "学校＿行きます (Gakkou _ ikimasu - Go to school). Fill blank.", options: [QuizOption(text: "へ/に", isCorrect: true), QuizOption(text: "で", isCorrect: false), QuizOption(text: "と", isCorrect: false), QuizOption(text: "も", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "図書館＿勉強します (Toshokan _ benkyou shimasu - Study AT the library). Fill blank.", options: [QuizOption(text: "に", isCorrect: false), QuizOption(text: "で", isCorrect: true), QuizOption(text: "を", isCorrect: false), QuizOption(text: "へ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "わたし＿学生です (Watashi _ gakusei desu - I AM a student). Fill blank.", options: [QuizOption(text: "が", isCorrect: false), QuizOption(text: "も", isCorrect: false), QuizOption(text: "は", isCorrect: true), QuizOption(text: "と", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "田中さん＿鈴木さん (Tanaka-san _ Suzuki-san - Mr. Tanaka AND Mr. Suzuki). Fill blank.", options: [QuizOption(text: "を", isCorrect: false), QuizOption(text: "に", isCorrect: false), QuizOption(text: "と", isCorrect: true), QuizOption(text: "で", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "ペン＿書きます (Pen _ kakimasu - Write WITH a pen). Fill blank.", options: [QuizOption(text: "を", isCorrect: false), QuizOption(text: "で", isCorrect: true), QuizOption(text: "と", isCorrect: false), QuizOption(text: "が", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "日本＿来ました (Nihon _ kimashita - Came FROM Japan). Fill blank.", options: [QuizOption(text: "に", isCorrect: false), QuizOption(text: "へ", isCorrect: false), QuizOption(text: "から", isCorrect: true), QuizOption(text: "で", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "五時＿起きます (Goji _ okimasu - Wake up AT 5 o'clock). Fill blank.", options: [QuizOption(text: "に", isCorrect: true), QuizOption(text: "で", isCorrect: false), QuizOption(text: "と", isCorrect: false), QuizOption(text: "から", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "パン＿ミルク (Pan _ miruku - Bread AND milk). Fill blank.", options: [QuizOption(text: "は", isCorrect: false), QuizOption(text: "が", isCorrect: false), QuizOption(text: "と", isCorrect: true), QuizOption(text: "を", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "ケーキ＿食べました (Keeki _ tabemashita - Ate cake). Fill blank.", options: [QuizOption(text: "は", isCorrect: false), QuizOption(text: "が", isCorrect: false), QuizOption(text: "を", isCorrect: true), QuizOption(text: "に", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "私はテニス＿好きです (Watashi wa tenisu _ suki desu - I like tennis). Fill blank.", options: [QuizOption(text: "を", isCorrect: false), QuizOption(text: "は", isCorrect: false), QuizOption(text: "が", isCorrect: true), QuizOption(text: "で", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "日本語＿話せます (Nihongo _ hanasemasu - I can speak Japanese). Fill blank with potential particle.", options: [QuizOption(text: "を", isCorrect: false), QuizOption(text: "に", isCorrect: false), QuizOption(text: "が", isCorrect: true), QuizOption(text: "へ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "この本は日本＿です (Kono hon wa Nihon _ desu - This book is FROM Japan). Fill blank.", options: [QuizOption(text: "に", isCorrect: false), QuizOption(text: "から", isCorrect: true), QuizOption(text: "で", isCorrect: false), QuizOption(text: "へ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "バス＿行きます (Basu _ ikimasu - Go BY bus). Fill blank.", options: [QuizOption(text: "に", isCorrect: false), QuizOption(text: "を", isCorrect: false), QuizOption(text: "で", isCorrect: true), QuizOption(text: "と", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "友達＿会います (Tomodachi _ aimasu - Meet a friend). Fill blank.", options: [QuizOption(text: "と", isCorrect: true), QuizOption(text: "を", isCorrect: false), QuizOption(text: "が", isCorrect: false), QuizOption(text: "は", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "彼＿電話しました (Kare _ denwa shimashita - Called him). Fill blank.", options: [QuizOption(text: "を", isCorrect: false), QuizOption(text: "に", isCorrect: true), QuizOption(text: "が", isCorrect: false), QuizOption(text: "と", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "部屋＿出ます (Heya _ demasu - Leave the room). Fill blank.", options: [QuizOption(text: "に", isCorrect: false), QuizOption(text: "を", isCorrect: true), QuizOption(text: "で", isCorrect: false), QuizOption(text: "から", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "椅子＿座ります (Isu _ suwarimasu - Sit ON a chair). Fill blank.", options: [QuizOption(text: "に", isCorrect: true), QuizOption(text: "で", isCorrect: false), QuizOption(text: "へ", isCorrect: false), QuizOption(text: "を", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "パーティー＿行きました (Paatii _ ikimashita - Went TO the party). Fill blank.", options: [QuizOption(text: "に", isCorrect: true), QuizOption(text: "で", isCorrect: false), QuizOption(text: "を", isCorrect: false), QuizOption(text: "から", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "日本酒＿飲んだことがありますか (Nihonshu _ nonda koto ga arimasu ka - Have you ever drunk sake?). Fill blank.", options: [QuizOption(text: "は", isCorrect: false), QuizOption(text: "が", isCorrect: true), QuizOption(text: "を", isCorrect: false), QuizOption(text: "と", isCorrect: false)], questionType: .multipleChoice)
    ]

    static let kanjiN4ChallengeQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Meaning of '会'?", options: [QuizOption(text: "Rest", isCorrect: false), QuizOption(text: "Say", isCorrect: false), QuizOption(text: "Meet", isCorrect: true), QuizOption(text: "Eat", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Reading of '同じ' (same)?", options: [QuizOption(text: "chigau", isCorrect: false), QuizOption(text: "onaji", isCorrect: true), QuizOption(text: "sukoshi", isCorrect: false), QuizOption(text: "hayai", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '強' (strong)?", options: [QuizOption(text: "よわ.い", isCorrect: false), QuizOption(text: "つよ.い", isCorrect: true), QuizOption(text: "おも.い", isCorrect: false), QuizOption(text: "かる.い", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '事'?", options: [QuizOption(text: "Person", isCorrect: false), QuizOption(text: "Thing, Matter", isCorrect: true), QuizOption(text: "Place", isCorrect: false), QuizOption(text: "Time", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '社' (company)?", options: [QuizOption(text: "やしろ", isCorrect: false), QuizOption(text: "シャ", isCorrect: true), QuizOption(text: "ショ", isCorrect: false), QuizOption(text: "ジン", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji means 'make' (作)?", options: [QuizOption(text: "書", isCorrect: false), QuizOption(text: "読", isCorrect: false), QuizOption(text: "作", isCorrect: true), QuizOption(text: "買", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Reading of '持つ' (to hold)?", options: [QuizOption(text: "motsu", isCorrect: true), QuizOption(text: "tatsu", isCorrect: false), QuizOption(text: "kaku", isCorrect: false), QuizOption(text: "miru", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '家'?", options: [QuizOption(text: "Store", isCorrect: false), QuizOption(text: "School", isCorrect: false), QuizOption(text: "House, Family", isCorrect: true), QuizOption(text: "Station", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '世' (world)?", options: [QuizOption(text: "よ", isCorrect: false), QuizOption(text: "セイ / セ", isCorrect: true), QuizOption(text: "カイ", isCorrect: false), QuizOption(text: "シュウ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji means 'many' (多)?", options: [QuizOption(text: "少", isCorrect: false), QuizOption(text: "大", isCorrect: false), QuizOption(text: "多", isCorrect: true), QuizOption(text: "小", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '正'?", options: [QuizOption(text: "Wrong", isCorrect: false), QuizOption(text: "Correct, Right", isCorrect: true), QuizOption(text: "Left", isCorrect: false), QuizOption(text: "Heavy", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Reading of '安い' (cheap)?", options: [QuizOption(text: "takai", isCorrect: false), QuizOption(text: "yasui", isCorrect: true), QuizOption(text: "furui", isCorrect: false), QuizOption(text: "atarashii", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji is 'heart' (心)?", options: [QuizOption(text: "手", isCorrect: false), QuizOption(text: "目", isCorrect: false), QuizOption(text: "心", isCorrect: true), QuizOption(text: "体", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '教' (teach)?", options: [QuizOption(text: "おし.える", isCorrect: false), QuizOption(text: "キョウ", isCorrect: true), QuizOption(text: "まな.ぶ", isCorrect: false), QuizOption(text: "ガク", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '聞'?", options: [QuizOption(text: "Speak", isCorrect: false), QuizOption(text: "Listen", isCorrect: true), QuizOption(text: "Read", isCorrect: false), QuizOption(text: "Write", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '言' (say)?", options: [QuizOption(text: "ゲン", isCorrect: false), QuizOption(text: "こと / い.う", isCorrect: true), QuizOption(text: "ご", isCorrect: false), QuizOption(text: "はな.す", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji means 'road' (道)?", options: [QuizOption(text: "駅", isCorrect: false), QuizOption(text: "道", isCorrect: true), QuizOption(text: "橋", isCorrect: false), QuizOption(text: "空", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Reading of '書く' (to write)?", options: [QuizOption(text: "yomu", isCorrect: false), QuizOption(text: "kaku", isCorrect: true), QuizOption(text: "hanasu", isCorrect: false), QuizOption(text: "kiku", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '読'?", options: [QuizOption(text: "Sing", isCorrect: false), QuizOption(text: "Draw", isCorrect: false), QuizOption(text: "Read", isCorrect: true), QuizOption(text: "Dance", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '思' (think)?", options: [QuizOption(text: "おも.う", isCorrect: false), QuizOption(text: "シ", isCorrect: true), QuizOption(text: "コウ", isCorrect: false), QuizOption(text: "ネン", isCorrect: false)], questionType: .multipleChoice)
    ]

    static let commonPhrasesQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "'Itadakimasu' is said...", options: [QuizOption(text: "Before eating", isCorrect: true), QuizOption(text: "After eating", isCorrect: false), QuizOption(text: "When meeting someone", isCorrect: false), QuizOption(text: "When leaving", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'Moshi moshi' is used for...", options: [QuizOption(text: "Greeting a teacher", isCorrect: false), QuizOption(text: "Answering the phone", isCorrect: true), QuizOption(text: "Saying goodbye", isCorrect: false), QuizOption(text: "Shopping", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "How to say 'You're welcome'?", options: [QuizOption(text: "ありがとう", isCorrect: false), QuizOption(text: "すみません", isCorrect: false), QuizOption(text: "どういたしまして", isCorrect: true), QuizOption(text: "おやすみ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What does 'Otsukaresama desu' mean?", options: [QuizOption(text: "Good morning", isCorrect: false), QuizOption(text: "Good work / Thank you for your effort", isCorrect: true), QuizOption(text: "Excuse me", isCorrect: false), QuizOption(text: "See you later", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "When do you say 'Gochisousama deshita'?", options: [QuizOption(text: "Before eating", isCorrect: false), QuizOption(text: "After finishing a meal", isCorrect: true), QuizOption(text: "When someone visits your home", isCorrect: false), QuizOption(text: "When you leave work", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which is a common way to say 'Excuse me' or 'I'm sorry'?", options: [QuizOption(text: "おはよう", isCorrect: false), QuizOption(text: "ありがとう", isCorrect: false), QuizOption(text: "すみません", isCorrect: true), QuizOption(text: "こんにちは", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'Tadaima' means...", options: [QuizOption(text: "I'm leaving", isCorrect: false), QuizOption(text: "I'm home", isCorrect: true), QuizOption(text: "Welcome home", isCorrect: false), QuizOption(text: "See you later", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is the response to 'Ittekimasu'?", options: [QuizOption(text: "ただいま", isCorrect: false), QuizOption(text: "おかえりなさい", isCorrect: false), QuizOption(text: "いってらっしゃい", isCorrect: true), QuizOption(text: "おやすみ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "To say 'Please' when making a request, you use:", options: [QuizOption(text: "ありがとう", isCorrect: false), QuizOption(text: "おねがいします", isCorrect: true), QuizOption(text: "ごめんなさい", isCorrect: false), QuizOption(text: "はい", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which phrase means 'Long time no see'?", options: [QuizOption(text: "はじめまして", isCorrect: false), QuizOption(text: "おひさしぶりです", isCorrect: true), QuizOption(text: "さようなら", isCorrect: false), QuizOption(text: "おげんきですか", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'Ganbatte' means...", options: [QuizOption(text: "Good job", isCorrect: false), QuizOption(text: "Do your best", isCorrect: true), QuizOption(text: "Thank you", isCorrect: false), QuizOption(text: "I'm sorry", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "To ask 'How are you?', you say:", options: [QuizOption(text: "おなまえは？", isCorrect: false), QuizOption(text: "おげんきですか？", isCorrect: true), QuizOption(text: "なんさいですか？", isCorrect: false), QuizOption(text: "どこですか？", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which is used to apologize?", options: [QuizOption(text: "ありがとう", isCorrect: false), QuizOption(text: "ごめんなさい", isCorrect: true), QuizOption(text: "こんにちは", isCorrect: false), QuizOption(text: "どうぞ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "When offering something, you might say:", options: [QuizOption(text: "はい", isCorrect: false), QuizOption(text: "いいえ", isCorrect: false), QuizOption(text: "どうぞ", isCorrect: true), QuizOption(text: "すみません", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "To say 'Good night' (to sleep), you use:", options: [QuizOption(text: "おはよう", isCorrect: false), QuizOption(text: "こんにちは", isCorrect: false), QuizOption(text: "おやすみ", isCorrect: true), QuizOption(text: "さようなら", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'Omedetou' means...", options: [QuizOption(text: "Thank you", isCorrect: false), QuizOption(text: "Congratulations", isCorrect: true), QuizOption(text: "Goodbye", isCorrect: false), QuizOption(text: "Excuse me", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which phrase is common when visiting someone's home?", options: [QuizOption(text: "ただいま", isCorrect: false), QuizOption(text: "おじゃまします", isCorrect: true), QuizOption(text: "いってきます", isCorrect: false), QuizOption(text: "ごちそうさま", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "When someone says 'Thank you' (ありがとう), a polite response is:", options: [QuizOption(text: "すみません", isCorrect: false), QuizOption(text: "どうぞ", isCorrect: false), QuizOption(text: "どういたしまして", isCorrect: true), QuizOption(text: "はい", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "To politely say 'please take care of me' or 'nice to meet you' when starting a new relationship:", options: [QuizOption(text: "おつかれさまです", isCorrect: false), QuizOption(text: "よろしくおねがいします", isCorrect: true), QuizOption(text: "しつれいします", isCorrect: false), QuizOption(text: "おきのどくに", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "You answer the phone with:", options: [QuizOption(text: "もしもし", isCorrect: true), QuizOption(text: "こんにちは", isCorrect: false), QuizOption(text: "はい", isCorrect: false), QuizOption(text: "ありがとう", isCorrect: false)], questionType: .multipleChoice)
    ]

    // --- EXPERT QUIZZES (Contoh Awal) ---
    static let kanjiN3DeepDiveQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Meaning of '受' in 受ける?", options: [QuizOption(text: "Give", isCorrect: false), QuizOption(text: "Receive/Take (exam)", isCorrect: true), QuizOption(text: "Send", isCorrect: false), QuizOption(text: "Refuse", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '進' (advance)?", options: [QuizOption(text: "シン", isCorrect: true), QuizOption(text: "セン", isCorrect: false), QuizOption(text: "シュ", isCorrect: false), QuizOption(text: "キン", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '様' (sama)?", options: [QuizOption(text: "Like, Resembling", isCorrect: false), QuizOption(text: "Mr./Ms., Manner, Appearance", isCorrect: true), QuizOption(text: "To decide", isCorrect: false), QuizOption(text: "To fight", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji means 'department' (部)?", options: [QuizOption(text: "課", isCorrect: false), QuizOption(text: "局", isCorrect: false), QuizOption(text: "部", isCorrect: true), QuizOption(text: "科", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Reading of '決める' (to decide)?", options: [QuizOption(text: "sadamaru", isCorrect: false), QuizOption(text: "kimeru", isCorrect: true), QuizOption(text: "tsutaeru", isCorrect: false), QuizOption(text: "shiraberu", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '全'?", options: [QuizOption(text: "Half", isCorrect: false), QuizOption(text: "Few", isCorrect: false), QuizOption(text: "All, Entire", isCorrect: true), QuizOption(text: "None", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '表' (surface)?", options: [QuizOption(text: "おもて", isCorrect: false), QuizOption(text: "ヒョウ", isCorrect: true), QuizOption(text: "あらわ.す", isCorrect: false), QuizOption(text: "ケン", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '戦' (war)?", options: [QuizOption(text: "セン", isCorrect: false), QuizOption(text: "たたか.う / いくさ", isCorrect: true), QuizOption(text: "カク", isCorrect: false), QuizOption(text: "ケン", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji implies 'pass through' (経)?", options: [QuizOption(text: "道", isCorrect: false), QuizOption(text: "越", isCorrect: false), QuizOption(text: "経", isCorrect: true), QuizOption(text: "通", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '最'?", options: [QuizOption(text: "Least", isCorrect: false), QuizOption(text: "Most, Extreme", isCorrect: true), QuizOption(text: "Middle", isCorrect: false), QuizOption(text: "First", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Reading of '現れる' (to appear)?", options: [QuizOption(text: "shimeru", isCorrect: false), QuizOption(text: "arawareru", isCorrect: true), QuizOption(text: "mieru", isCorrect: false), QuizOption(text: "nozomu", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '調' (investigate)?", options: [QuizOption(text: "しら.べる", isCorrect: false), QuizOption(text: "チョウ", isCorrect: true), QuizOption(text: "トウ", isCorrect: false), QuizOption(text: "ケン", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji refers to 'people' (民)?", options: [QuizOption(text: "人", isCorrect: false), QuizOption(text: "氏", isCorrect: false), QuizOption(text: "民", isCorrect: true), QuizOption(text: "族", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '連'?", options: [QuizOption(text: "Separate", isCorrect: false), QuizOption(text: "Break", isCorrect: false), QuizOption(text: "Connect, Take along", isCorrect: true), QuizOption(text: "Hide", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '相' (mutual)?", options: [QuizOption(text: "ソウ", isCorrect: false), QuizOption(text: "ショウ", isCorrect: false), QuizOption(text: "あい-", isCorrect: true), QuizOption(text: "たが.い", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which Kanji means 'district' (区)?", options: [QuizOption(text: "市", isCorrect: false), QuizOption(text: "町", isCorrect: false), QuizOption(text: "区", isCorrect: true), QuizOption(text: "村", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '実'?", options: [QuizOption(text: "Fake", isCorrect: false), QuizOption(text: "Truth, Fruit, Reality", isCorrect: true), QuizOption(text: "Dream", isCorrect: false), QuizOption(text: "Empty", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "On'yomi of '化' (change)?", options: [QuizOption(text: "ば.ける", isCorrect: false), QuizOption(text: "カ / ケ", isCorrect: true), QuizOption(text: "ヘン", isCorrect: false), QuizOption(text: "ヘイ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Kun'yomi of '定' (decide)?", options: [QuizOption(text: "テイ", isCorrect: false), QuizOption(text: "ジョウ", isCorrect: false), QuizOption(text: "さだ.める / さだ.まる", isCorrect: true), QuizOption(text: "き.める", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '議'?", options: [QuizOption(text: "Sing", isCorrect: false), QuizOption(text: "Discuss, Deliberate", isCorrect: true), QuizOption(text: "Teach", isCorrect: false), QuizOption(text: "Run", isCorrect: false)], questionType: .multipleChoice)
    ]

    static let advancedGrammarStructuresQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Which expresses 'must do': ～なければならない or ～てもいい?", options: [QuizOption(text: "～なければならない", isCorrect: true), QuizOption(text: "～てもいい", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Passive form of 食べる (taberu)?", options: [QuizOption(text: "食べさせる", isCorrect: false), QuizOption(text: "食べられる", isCorrect: true), QuizOption(text: "食べたがる", isCorrect: false), QuizOption(text: "食べない", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Causative-passive form of 書く (kaku) 'to write' (to be made to write)?", options: [QuizOption(text: "書かれる", isCorrect: false), QuizOption(text: "書かせる", isCorrect: false), QuizOption(text: "書かせられる", isCorrect: true), QuizOption(text: "書きたくない", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "To say 'I regret doing X' or 'I wish I hadn't done X', you use:", options: [QuizOption(text: "～ても", isCorrect: false), QuizOption(text: "～なければ", isCorrect: false), QuizOption(text: "～てしまう", isCorrect: false), QuizOption(text: "～ておく", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which indicates an ongoing action or state?", options: [QuizOption(text: "～てみる", isCorrect: false), QuizOption(text: "～ている", isCorrect: true), QuizOption(text: "～ておく", isCorrect: false), QuizOption(text: "～てしまう", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "The form for 'seemingly' or 'it looks like' (based on observation):", options: [QuizOption(text: "～そうだ (伝聞)", isCorrect: false), QuizOption(text: "～そうだ (様態)", isCorrect: true), QuizOption(text: "～ようだ", isCorrect: false), QuizOption(text: "～らしい", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which expresses 'even if... / even though...'?", options: [QuizOption(text: "～から", isCorrect: false), QuizOption(text: "～けれども", isCorrect: false), QuizOption(text: "～ても", isCorrect: true), QuizOption(text: "～ので", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "The structure to express 'become X' or 'turn into X' for adjectives:", options: [QuizOption(text: "Adj-i + なる / Adj-na + になる", isCorrect: true), QuizOption(text: "Adj-i + になる / Adj-na + になる", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "Which conveys a sense of having just done something?", options: [QuizOption(text: "～たばかり", isCorrect: true), QuizOption(text: "～たことがある", isCorrect: false), QuizOption(text: "～ているところ", isCorrect: false), QuizOption(text: "～ところだ", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "The particle used to mark the *target* of a passive action:", options: [QuizOption(text: "が", isCorrect: false), QuizOption(text: "を", isCorrect: false), QuizOption(text: "に", isCorrect: true), QuizOption(text: "で", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which form suggests 'try doing X'?", options: [QuizOption(text: "～てしまう", isCorrect: false), QuizOption(text: "～てみる", isCorrect: true), QuizOption(text: "～ておく", isCorrect: false), QuizOption(text: "～てください", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "The conditional form for a natural or inevitable consequence:", options: [QuizOption(text: "～たら", isCorrect: false), QuizOption(text: "～ば", isCorrect: false), QuizOption(text: "～と", isCorrect: true), QuizOption(text: "～なら", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "To indicate 'preparation' for an action, you use:", options: [QuizOption(text: "～ていく", isCorrect: false), QuizOption(text: "～てくる", isCorrect: false), QuizOption(text: "～ておく", isCorrect: true), QuizOption(text: "～てあげる", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which expresses 'it is said that...' or 'I hear that...'?", options: [QuizOption(text: "～そうだ (様態)", isCorrect: false), QuizOption(text: "～そうだ (伝聞)", isCorrect: true), QuizOption(text: "～ようだ", isCorrect: false), QuizOption(text: "～らしい", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "To express 'I have decided to do X', you use:", options: [QuizOption(text: "～ことにする", isCorrect: true), QuizOption(text: "～ことにしている", isCorrect: false), QuizOption(text: "～ことにした", isCorrect: false), QuizOption(text: "～ことにしよう", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "The causative form of verbs is used to express making or letting someone do something. True or False?", options: [QuizOption(text: "True", isCorrect: true), QuizOption(text: "False", isCorrect: false)], questionType: .trueFalse),
        QuizQuestion(questionText: "When asking for permission, which structure is correct?", options: [QuizOption(text: "～てもいいですか", isCorrect: true), QuizOption(text: "～てはいけません", isCorrect: false), QuizOption(text: "～なければならない", isCorrect: false), QuizOption(text: "～たほうがいい", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which indicates an action completed entirely, often with regret?", options: [QuizOption(text: "～ておく", isCorrect: false), QuizOption(text: "～てあげる", isCorrect: false), QuizOption(text: "～てしまう", isCorrect: true), QuizOption(text: "～てくれる", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "The structure 'V-dictionary + ことができます' means:", options: [QuizOption(text: "Can do V", isCorrect: true), QuizOption(text: "Must do V", isCorrect: false), QuizOption(text: "Want to do V", isCorrect: false), QuizOption(text: "Don't do V", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Which form emphasizes the reason or cause for something?", options: [QuizOption(text: "～が", isCorrect: false), QuizOption(text: "～から", isCorrect: true), QuizOption(text: "～て", isCorrect: false), QuizOption(text: "～と", isCorrect: false)], questionType: .multipleChoice)
    ]

    static let expertVocabularyIdiomsQuiz: [QuizQuestion] = [
        QuizQuestion(questionText: "Meaning of '一期一会' (ichigo ichie)?", options: [QuizOption(text: "Once in a lifetime encounter", isCorrect: true), QuizOption(text: "Hard work pays off", isCorrect: false), QuizOption(text: "Many people, many minds", isCorrect: false), QuizOption(text: "All is fair in love and war", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'画竜点睛を欠く' (garyou tensei wo kaku) means something is missing the...", options: [QuizOption(text: "Starting point", isCorrect: false), QuizOption(text: "Main body", isCorrect: false), QuizOption(text: "Finishing touch", isCorrect: true), QuizOption(text: "Foundation", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '棚から牡丹餅' (tana kara botamochi)?", options: [QuizOption(text: "A difficult task", isCorrect: false), QuizOption(text: "A windfall / unexpected good fortune", isCorrect: true), QuizOption(text: "A hidden danger", isCorrect: false), QuizOption(text: "A beautiful sight", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What does '石の上にも三年' (ishi no ue nimo san nen) imply?", options: [QuizOption(text: "Patience will be rewarded", isCorrect: true), QuizOption(text: "Stones are hard", isCorrect: false), QuizOption(text: "Three years is a long time", isCorrect: false), QuizOption(text: "Don't sit on cold stones", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'猫の手も借りたい' (neko no te mo karitai) describes a situation where you are:", options: [QuizOption(text: "Feeling lazy", isCorrect: false), QuizOption(text: "Extremely busy and desperate for help", isCorrect: true), QuizOption(text: "Playing with cats", isCorrect: false), QuizOption(text: "Afraid of cats", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '馬の耳に念仏' (uma no mimi ni nenbutsu)?", options: [QuizOption(text: "To pray for horses", isCorrect: false), QuizOption(text: "Talking to a brick wall (wasted effort)", isCorrect: true), QuizOption(text: "Horses like music", isCorrect: false), QuizOption(text: "Buddhist chanting is good for animals", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'口は災いの元' (kuchi wa wazawai no moto) means:", options: [QuizOption(text: "Words can cause trouble", isCorrect: true), QuizOption(text: "Be careful what you eat", isCorrect: false), QuizOption(text: "The mouth is the source of happiness", isCorrect: false), QuizOption(text: "Speaking is easy", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What does '聞くは一時の恥、聞かぬは一生の恥' (kiku wa ichiji no haji, kikanu wa isshou no haji) suggest?", options: [QuizOption(text: "It's shameful to ask questions", isCorrect: false), QuizOption(text: "Asking is a moment's shame, not asking is a lifetime's shame", isCorrect: true), QuizOption(text: "Listen to others always", isCorrect: false), QuizOption(text: "Shame lasts a lifetime", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'案ずるより産むが易し' (anzuru yori umu ga yasushi) means:", options: [QuizOption(text: "Thinking is easier than doing", isCorrect: false), QuizOption(text: "It's easier to do than to worry about it", isCorrect: true), QuizOption(text: "Worrying helps you prepare", isCorrect: false), QuizOption(text: "Birth is easy", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '三日坊主' (mikka bouzu)?", options: [QuizOption(text: "A monk who studies for three days", isCorrect: false), QuizOption(text: "Someone who gives up easily / a fickle person", isCorrect: true), QuizOption(text: "A three-day festival", isCorrect: false), QuizOption(text: "A bald person for three days", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'水に流す' (mizu ni nagasu) means to:", options: [QuizOption(text: "Pour water", isCorrect: false), QuizOption(text: "Let bygones be bygones / Forgive and forget", isCorrect: true), QuizOption(text: "Wash something with water", isCorrect: false), QuizOption(text: "Sail on water", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What is '猿も木から落ちる' (saru mo ki kara ochiru)?", options: [QuizOption(text: "Monkeys love trees", isCorrect: false), QuizOption(text: "Even monkeys fall from trees (even experts make mistakes)", isCorrect: true), QuizOption(text: "Don't climb trees with monkeys", isCorrect: false), QuizOption(text: "Falling is easy for monkeys", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '郷に入っては郷に従え' (gou ni itte wa gou ni shitagae)?", options: [QuizOption(text: "Follow your own rules", isCorrect: false), QuizOption(text: "When in Rome, do as the Romans do", isCorrect: true), QuizOption(text: "Stay in your own country", isCorrect: false), QuizOption(text: "Obey the local laws", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'七転び八起き' (nana korobi ya oki) refers to:", options: [QuizOption(text: "Falling seven times and standing up eight (perseverance)", isCorrect: true), QuizOption(text: "A lucky number", isCorrect: false), QuizOption(text: "Sleeping seven hours and waking up eight", isCorrect: false), QuizOption(text: "Seven falls, eight rises", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What does '花より団子' (hana yori dango) mean?", options: [QuizOption(text: "Dango tastes better than flowers", isCorrect: false), QuizOption(text: "Substance over show / Practicality over aesthetics", isCorrect: true), QuizOption(text: "Flowers are better than dango", isCorrect: false), QuizOption(text: "Enjoy both flowers and dango", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '自業自得' (jigou jitoku)?", options: [QuizOption(text: "Self-made success", isCorrect: false), QuizOption(text: "You reap what you sow / Just deserts", isCorrect: true), QuizOption(text: "Self-improvement", isCorrect: false), QuizOption(text: "Doing things yourself", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'油を売る' (abura o uru) means to:", options: [QuizOption(text: "Sell oil", isCorrect: false), QuizOption(text: "Chat idly / Waste time", isCorrect: true), QuizOption(text: "Work hard", isCorrect: false), QuizOption(text: "Buy oil", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "What does '二足のわらじを履く' (nisoku no waraji o haku) suggest?", options: [QuizOption(text: "Wearing two pairs of sandals", isCorrect: false), QuizOption(text: "Doing two things at once / Having two jobs", isCorrect: true), QuizOption(text: "Walking on two feet", isCorrect: false), QuizOption(text: "Being well-prepared", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "Meaning of '焼け石に水' (yakeishi ni mizu)?", options: [QuizOption(text: "Water on a hot stone (a drop in the bucket)", isCorrect: true), QuizOption(text: "Making stones hot with water", isCorrect: false), QuizOption(text: "Burning water", isCorrect: false), QuizOption(text: "Water extinguishes fire", isCorrect: false)], questionType: .multipleChoice),
        QuizQuestion(questionText: "'鬼に金棒' (oni ni kanabou) means:", options: [QuizOption(text: "A demon with a club (strengthening the strong)", isCorrect: true), QuizOption(text: "Demons are powerful", isCorrect: false), QuizOption(text: "Give a club to a demon", isCorrect: false), QuizOption(text: "A strong demon needs no weapons", isCorrect: false)], questionType: .multipleChoice)
    ]


    // Update Helper untuk mendapatkan pertanyaan
    static func getQuestions(forQuizTitle title: String) -> [QuizQuestion] {
        switch title {
        // Beginner
        case "Hiragana Basics Quiz": return hiraganaBasicsQuiz.shuffled()
        case "Katakana Basics Quiz": return katakanaBasicsQuiz.shuffled()
        case "Kanji N5 Starter Quiz": return kanjiN5StarterQuiz.shuffled()
        // Intermediate
        case "Intermediate Grammar Particles": return intermediateGrammarParticlesQuiz.shuffled()
        case "Kanji N4 Challenge": return kanjiN4ChallengeQuiz.shuffled()
        case "Common Phrases Quiz": return commonPhrasesQuiz.shuffled()
        // Expert
        case "Kanji N3 Deep Dive": return kanjiN3DeepDiveQuiz.shuffled()
        case "Advanced Grammar Structures": return advancedGrammarStructuresQuiz.shuffled()
        case "Expert Vocabulary & Idioms": return expertVocabularyIdiomsQuiz.shuffled()
        default:
            print("Warning: Quiz title '\(title)' not found in QuizData. Returning empty set.")
            return []
        }
    }
}
