import Foundation

// Struct untuk satu frasa latihan berbicara
struct SpeakingPhrase: Identifiable {
    let id = UUID()
    let courseTitle: String // Judul kursus/kategori asal frasa ini
    let korean: String      // Frasa dalam Hangul
    let romaji: String      // Romanisasi
    let english: String     // Terjemahan Inggris
}

// Struct untuk menyediakan data latihan berbicara
struct KoreanSpeakingData {

    static let allPhrases: [SpeakingPhrase] = [
        // --- PERUBAHAN: Ganti courseTitle ke Bahasa Inggris ---
        // --- Kategori: Basic Conversation ---
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "안녕하세요.",
                       romaji: "Annyeonghaseyo.",
                       english: "Hello / Hi / Good morning / Good afternoon / Good evening."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "반갑습니다.",
                       romaji: "Bangapseumnida.",
                       english: "Nice to meet you."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "감사합니다.",
                       romaji: "Gamsahamnida.",
                       english: "Thank you."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "고맙습니다.",
                       romaji: "Gomapseumnida.",
                       english: "Thank you. (slightly less formal than Gamsahamnida)"),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "천만에요.",
                       romaji: "Cheonmaneyo.",
                       english: "You're welcome."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "죄송합니다.",
                       romaji: "Joesonghamnida.",
                       english: "I am sorry. (formal)"),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "미안합니다.",
                       romaji: "Mianhamnida.",
                       english: "I am sorry. (polite)"),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "괜찮아요.",
                       romaji: "Gwaenchanayo.",
                       english: "It's okay / I'm okay / It's alright."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "네.",
                       romaji: "Ne.",
                       english: "Yes / Okay / I see."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "아니요.",
                       romaji: "Aniyo.",
                       english: "No."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "잘 지냈어요?",
                       romaji: "Jal jinaesseoyo?",
                       english: "How have you been? / Did you have a good time?"),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "네, 잘 지냈어요.",
                       romaji: "Ne, jal jinaesseoyo.",
                       english: "Yes, I've been well."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "안녕히 가세요.",
                       romaji: "Annyeonghi gaseyo.",
                       english: "Goodbye (to someone who is leaving)."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "안녕히 계세요.",
                       romaji: "Annyeonghi gyeseyo.",
                       english: "Goodbye (when you are the one leaving)."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "또 만나요.",
                       romaji: "Tto mannayo.",
                       english: "See you later."),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "이름이 뭐예요?",
                       romaji: "Ireumi mwoyeyo?",
                       english: "What's your name?"),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "이것은 뭐예요?",
                       romaji: "Igeoseun mwoyeyo?",
                       english: "What is this?"),
        SpeakingPhrase(courseTitle: "Basic Conversation",
                       korean: "얼마예요?",
                       romaji: "Eolmayeyo?",
                       english: "How much is it?"),

        // --- Kategori: Self Introduction ---
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "제 이름은 김민준입니다.",
                       romaji: "Je ireumeun Kim Minjun-imnida.",
                       english: "My name is Kim Minjun."),
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "저는 한국에서 왔어요.",
                       romaji: "Jeoneun hanguk-eseo wasseoyo.",
                       english: "I am from Korea."),
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "저는 학생입니다.",
                       romaji: "Jeoneun haksaeng-imnida.",
                       english: "I am a student."),
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "만나서 반갑습니다.",
                       romaji: "Mannaseo bangapseumnida.",
                       english: "It's a pleasure to meet you."),
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "나이가 어떻게 되세요?",
                       romaji: "Na-iga eotteoke doeseyo?",
                       english: "How old are you? (polite)"),
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "저는 스무 살입니다.",
                       romaji: "Jeoneun seumu sal-imnida.",
                       english: "I am twenty years old."),
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "취미가 뭐예요?",
                       romaji: "Chwimiga mwoyeyo?",
                       english: "What are your hobbies?"),
        SpeakingPhrase(courseTitle: "Self Introduction",
                       korean: "제 취미는 독서입니다.",
                       romaji: "Je chwimineun dokseo-imnida.",
                       english: "My hobby is reading."),

        // --- Kategori: At the Restaurant ---
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "자리 있어요?",
                       romaji: "Jari isseoyo?",
                       english: "Do you have a table/seat?"),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "메뉴 좀 주세요.",
                       romaji: "Menyu jom juseyo.",
                       english: "Please give me the menu."),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "주문할게요.",
                       romaji: "Jumunhalgeyo.",
                       english: "I'd like to order."),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "이거 주세요.",
                       romaji: "Igeo juseyo.",
                       english: "Please give me this one."),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "물 좀 주세요.",
                       romaji: "Mul jom juseyo.",
                       english: "Please give me some water."),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "김치 좀 더 주세요.",
                       romaji: "Kimchi jom deo juseyo.",
                       english: "Please give me some more kimchi."),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "이거 매워요?",
                       romaji: "Igeo maewoyo?",
                       english: "Is this spicy?"),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "안 맵게 해주세요.",
                       romaji: "An maepge haejuseyo.",
                       english: "Please make it not spicy."),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "맛있어요!",
                       romaji: "Masisseoyo!",
                       english: "It's delicious!"),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "잘 먹겠습니다.",
                       romaji: "Jal meokgetseumnida.",
                       english: "I will eat well. (Said before a meal)"),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "잘 먹었습니다.",
                       romaji: "Jal meogeotseumnida.",
                       english: "I ate well. (Said after a meal)"),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "계산서 주세요.",
                       romaji: "Gyesanseo juseyo.",
                       english: "Please give me the bill/check."),
        SpeakingPhrase(courseTitle: "At the Restaurant",
                       korean: "화장실 어디예요?",
                       romaji: "Hwajangsil eodiyeyo?",
                       english: "Where is the restroom?")
    ]

    // Fungsi ini tidak perlu diubah karena sudah menggunakan .lowercased()
    static func phrases(forCourseTitle title: String) -> [SpeakingPhrase] {
        return allPhrases.filter { $0.courseTitle.lowercased() == title.lowercased() }.shuffled() // Acak urutan frasa
    }
}
